//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryType", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework")]
    [System.SerializableAttribute()]
    public partial class QueryType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookType", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework")]
    [System.SerializableAttribute()]
    public partial class BookType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApp.ServiceReference1.AuthorType[] authorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((this.SignatureField.Equals(value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApp.ServiceReference1.AuthorType[] authors {
            get {
                return this.authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.authorsField, value) != true)) {
                    this.authorsField = value;
                    this.RaisePropertyChanged("authors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorType", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework")]
    [System.SerializableAttribute()]
    public partial class AuthorType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LibrarySearchingException", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework.Exceptions")]
    [System.SerializableAttribute()]
    public partial class LibrarySearchingException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationType {
            get {
                return this.OperationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationTypeField, value) != true)) {
                    this.OperationTypeField = value;
                    this.RaisePropertyChanged("OperationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WrongSignatureException", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework.Exceptions")]
    [System.SerializableAttribute()]
    public partial class WrongSignatureException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationType {
            get {
                return this.OperationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationTypeField, value) != true)) {
                    this.OperationTypeField = value;
                    this.RaisePropertyChanged("OperationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchLibrary", ReplyAction="http://tempuri.org/IService1/SearchLibraryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApp.ServiceReference1.LibrarySearchingException), Action="http://tempuri.org/IService1/SearchLibraryLibrarySearchingExceptionFault", Name="LibrarySearchingException", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework.Exceptions")]
        ClientApp.ServiceReference1.BookType[] SearchLibrary(ClientApp.ServiceReference1.QueryType Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchLibrary", ReplyAction="http://tempuri.org/IService1/SearchLibraryResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference1.BookType[]> SearchLibraryAsync(ClientApp.ServiceReference1.QueryType Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrowBook", ReplyAction="http://tempuri.org/IService1/BorrowBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApp.ServiceReference1.WrongSignatureException), Action="http://tempuri.org/IService1/BorrowBookWrongSignatureExceptionFault", Name="WrongSignatureException", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework.Exceptions")]
        ClientApp.ServiceReference1.BookType BorrowBook(int Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrowBook", ReplyAction="http://tempuri.org/IService1/BorrowBookResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference1.BookType> BorrowBookAsync(int Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnBook", ReplyAction="http://tempuri.org/IService1/ReturnBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApp.ServiceReference1.WrongSignatureException), Action="http://tempuri.org/IService1/ReturnBookWrongSignatureExceptionFault", Name="WrongSignatureException", Namespace="http://schemas.datacontract.org/2004/07/WcfHomework.Exceptions")]
        ClientApp.ServiceReference1.BookType ReturnBook(int Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnBook", ReplyAction="http://tempuri.org/IService1/ReturnBookResponse")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference1.BookType> ReturnBookAsync(int Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLibraryInfo", ReplyAction="http://tempuri.org/IService1/GetLibraryInfoResponse")]
        string GetLibraryInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLibraryInfo", ReplyAction="http://tempuri.org/IService1/GetLibraryInfoResponse")]
        System.Threading.Tasks.Task<string> GetLibraryInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientApp.ServiceReference1.IService1>, ClientApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApp.ServiceReference1.BookType[] SearchLibrary(ClientApp.ServiceReference1.QueryType Query) {
            return base.Channel.SearchLibrary(Query);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference1.BookType[]> SearchLibraryAsync(ClientApp.ServiceReference1.QueryType Query) {
            return base.Channel.SearchLibraryAsync(Query);
        }
        
        public ClientApp.ServiceReference1.BookType BorrowBook(int Signature) {
            return base.Channel.BorrowBook(Signature);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference1.BookType> BorrowBookAsync(int Signature) {
            return base.Channel.BorrowBookAsync(Signature);
        }
        
        public ClientApp.ServiceReference1.BookType ReturnBook(int Signature) {
            return base.Channel.ReturnBook(Signature);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference1.BookType> ReturnBookAsync(int Signature) {
            return base.Channel.ReturnBookAsync(Signature);
        }
        
        public string GetLibraryInfo() {
            return base.Channel.GetLibraryInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetLibraryInfoAsync() {
            return base.Channel.GetLibraryInfoAsync();
        }
    }
}
